apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orders-pubsub
spec:
  type: bindings.kafka
  version: v1
  metadata:
  - name: topics
    value: "orders"
  - name: consumerGroup
    value: "group1"
  - name: brokers
    value: "localhost:9092"
  - name: publishTopic
    value: orders
  - name: authRequired
    value: false